(() => {
  const app = document.querySelector('#app');
  // This fallback keeps the game fully usable when opened directly as a file,
  // where browsers block JSON fetches for security reasons.
  const fallbackWords = {
    Objects:['Backpack','Clock','Key'], Animals:['Dog','Tiger','Dolphin'], Food:['Pizza','Sushi','Pancakes'], Movies:['Titanic','Inception','Avatar'], 'TV Shows':['Friends','Sherlock','Wednesday'], 'Video Games':['Minecraft','Tetris','Fortnite'], Celebrities:['Taylor Swift','Tom Cruise','Zendaya'], Sports:['Football','Cricket','Tennis'], Countries:['India','Japan','Brazil'], Cities:['Mumbai','Tokyo','Paris'], Mythology:['Zeus','Thor','Medusa'], Science:['Gravity','Atom','Volcano'], Technology:['Smartphone','Internet','Drone'], 'Household Items':['Sofa','Toothbrush','Pillow'], Nature:['Waterfall','Mountain','Desert'], Plants:['Rose','Cactus','Bamboo'], Fruits:['Apple','Banana','Mango'], Vehicles:['Bicycle','Train','Airplane'], Music:['Guitar','Piano','Drums'], Jobs:['Doctor','Teacher','Chef']
  };
  let wordData = fallbackWords;
  let game = { screen: 'setup', count: 3, names: [], imposters: 1, category: 'Random', hint: true, viewed: [] };
  const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const secureIndex = (upperBound) => {
    const limit = Math.floor(0x100000000 / upperBound) * upperBound;
    const value = new Uint32Array(1);
    do { crypto.getRandomValues(value); } while (value[0] >= limit);
    return value[0] % upperBound;
  };
  const shuffle = (items) => { const copy = [...items]; for (let i = copy.length - 1; i > 0; i--) { const j = secureIndex(i + 1); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };
  const ensureNames = () => { game.names = Array.from({ length: game.count }, (_, i) => game.names[i]?.trim() || `Player ${i + 1}`); game.imposters = Math.min(game.imposters, game.count - 1); };
  const statusList = () => `<div class="player-status">${game.names.map((name,i) => `<div class="${game.viewed.includes(i) ? 'viewed' : 'waiting'}">${game.viewed.includes(i) ? '✓ Viewed' : '◌ Waiting'}<br><strong>${escapeHtml(name)}</strong></div>`).join('')}</div>`;
  function renderSetup() { ensureNames(); const categories = Object.keys(wordData); app.innerHTML = `<h1>Find the imposter.</h1><p class="lead">Give everyone a secret card, then figure out who is bluffing.</p><div class="field-grid"><label>Imposters<select id="imposters">${Array.from({length:game.count-1},(_,i)=>`<option value="${i+1}" ${game.imposters===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label><label>Secret category<select id="category"><option value="Random">Random category</option>${categories.map(c=>`<option ${game.category===c?'selected':''}>${escapeHtml(c)}</option>`).join('')}</select></label></div><div class="section-title"><h2>Players <span class="lead">(${game.count}/20)</span></h2><button class="button secondary add-player" id="add-player" ${game.count === 20 ? 'disabled' : ''}>＋ Add player</button></div><div class="names">${game.names.map((name,i)=>`<label class="name-row"><span>${i+1}</span><input data-name="${i}" type="text" maxlength="35" value="${escapeHtml(name)}" aria-label="Player ${i+1} name"></label>`).join('')}</div><label class="toggle"><input id="hint" type="checkbox" ${game.hint?'checked':''}><span>Show imposters the category as a hint</span></label><button class="button primary" id="start">Start game</button><p class="notice hidden" id="setup-error"></p>`;
    document.querySelector('#add-player').onclick = () => { if (game.count < 20) { game.count++; game.names.push(`Player ${game.count}`); renderSetup(); } };
    document.querySelector('#imposters').onchange = e => game.imposters = +e.target.value;
    document.querySelector('#category').onchange = e => game.category = e.target.value;
    document.querySelector('#hint').onchange = e => game.hint = e.target.checked;
    document.querySelectorAll('[data-name]').forEach(input => input.oninput = e => game.names[+e.target.dataset.name] = e.target.value);
    document.querySelector('#start').onclick = startGame;
  }
  function startGame() { ensureNames(); const duplicate = game.names.map(n=>n.toLowerCase()).some((n,i,a)=>a.indexOf(n)!==i); if (duplicate) { const error=document.querySelector('#setup-error');error.textContent='Please give each player a unique name.';error.classList.remove('hidden');return; } const category = game.category === 'Random' ? shuffle(Object.keys(wordData))[0] : game.category; const word = shuffle(wordData[category])[0]; game = { ...game, screen:'pass', current:0, viewed:[], category, word, imposterIndexes: shuffle(Array.from({length:game.count},(_,i)=>i)).slice(0,game.imposters) }; render(); }
  function renderPass() { const name = game.names[game.current]; app.innerHTML = `<div class="center"><p class="eyebrow">${game.current ? 'Next player' : 'Game ready'}</p><h1>Pass the device to</h1><p class="big-name">${escapeHtml(name)}</p><p class="lead">Make sure no one else can see the screen.</p><button class="button primary" id="ready">I'm ready</button>${statusList()}</div>`; document.querySelector('#ready').onclick=()=>{game.screen='reveal';render();}; }
  function renderReveal() { const name=game.names[game.current]; app.innerHTML=`<div class="center"><p class="eyebrow">Private card</p><h1>${escapeHtml(name)}</h1><p class="lead">Only you should look at this screen.</p><button class="button primary" id="show">Reveal card</button><div class="hidden" id="answer"></div>${statusList()}</div>`; document.querySelector('#show').onclick=()=>{const imposter=game.imposterIndexes.includes(game.current);document.querySelector('#show').classList.add('hidden');const answer=document.querySelector('#answer');answer.className='card-answer';answer.innerHTML=`<p class="eyebrow">Your role</p><div class="answer-word ${imposter?'imposter-word':''}">${imposter?'IMPOSTER':escapeHtml(game.word)}</div>${imposter&&game.hint?`<p class="hint">Category: ${escapeHtml(game.category)}</p>`:''}<button class="button primary" id="hide">Hide card</button>`;document.querySelector('#hide').onclick=hideCard;}; }
  function hideCard(){ if(!game.viewed.includes(game.current)) game.viewed.push(game.current); if(game.current<game.count-1){game.current++;game.screen='pass';}else game.screen='ready';render(); }
  function renderReady(){app.innerHTML=`<div class="center"><p class="eyebrow">All cards viewed</p><h1>Everyone is ready.</h1><p class="lead">Start the discussion when the group is together.</p>${statusList()}<button class="button primary" id="begin-discussion">Begin discussion</button></div>`;document.querySelector('#begin-discussion').onclick=()=>{game.screen='discussion';render();};}
  function renderDiscussion(){app.innerHTML=`<div class="center"><p class="eyebrow">All cards viewed</p><h1>Time to discuss.</h1><p class="lead">Talk it out in real life. When you are ready, reveal the answer.</p>${statusList()}<button class="button primary" id="results">Reveal imposters</button></div>`;document.querySelector('#results').onclick=()=>{game.screen='results';render();};}
  function renderResults(){const names=game.imposterIndexes.map(i=>escapeHtml(game.names[i])).join('<br>');app.innerHTML=`<div class="center"><p class="eyebrow">Case closed</p><h1>Here is the answer.</h1><div class="results"><div class="result-box"><p>Secret word</p><strong>${escapeHtml(game.word)}</strong><p>${escapeHtml(game.category)}</p></div><div class="result-box"><p>Imposter${game.imposterIndexes.length>1?'s':''}</p><strong>${names}</strong></div></div><button class="button primary" id="new-game">New game</button></div>`;document.querySelector('#new-game').onclick=()=>{game={screen:'setup',count:3,names:[],imposters:1,category:'Random',hint:true,viewed:[]};render();};}
  function render(){({setup:renderSetup,pass:renderPass,reveal:renderReveal,ready:renderReady,discussion:renderDiscussion,results:renderResults}[game.screen])();}
  fetch('../data/words.json').then(r=>r.ok?r.json():Promise.reject()).then(data=>{wordData=data;render();}).catch(render);
})();
